// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication2.Entities
{
    public partial class Fruitdev
    {

        public int id { get; set; }
        public string Nome { get; set; }

        public string dev { get; set; }
    }
}